---
- name: nginx provisioner
  hosts: all
  tasks:
    - name: install epel repository
      yum:
         name:
           - epel-release

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install a list of packages
      yum:
        name:
          - nginx
        state: present

    - name: Edit index.html
      command: echo "Hello World" >> /usr/share/nginx/html/index.html

    - name: Serve Hello World
      copy:
        src: files/index.html
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: 0777
